<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>workspace_gz</name>
  <version>0.0.1</version>
  <description>STI USV Simulation Package</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>ignition-gazebo6</build_depend>
  <build_depend>ignition-common4</build_depend>
  <build_depend>ignition-math6</build_depend>
  <build_depend>ignition-plugin1</build_depend>
  <build_depend>ignition-rendering6</build_depend>
  <build_depend>ignition-sensors6</build_depend>
  <build_depend>ignition-transport11</build_depend>
  <build_depend>ignition-utils1</build_depend>
  <build_depend>sdformat12</build_depend>
  <build_depend>eigen</build_depend>

  <depend>std_msgs</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>